version: "3.1"

services:
  app:
    build: ./.docker/php-fpm
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

  webserver:
    image: nginx:1.17.2-alpine
    working_dir: /app
    ports:
      - 8082:80
    volumes:
      - ./backend:/app
      - ./.certs:/nginx/certs/
  db:
    image: mysql:5.7.22
    container_name: db1
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf

  beanstalkd:
    image: schickling/beanstalkd:latest
